##UEF ACU Upgrades  

Description['gel0001'] = "<LOC Unit_Description_0303> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
Description['gel0001-aes'] = "<LOC Unit_Description_0005> Expands the number of available schematics and increases the ACU's build speed and maximum health."
Description['gel0001-dsu'] = "<LOC Unit_Description_0006> Greatly increases the speed at which the ACU repairs itself."
Description['gel0001-ees'] = "<LOC Unit_Description_0007> Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gel0001-hamc'] = "<LOC Unit_Description_GCE001> Increases range of main cannon."
Description['gel0001-srtn'] = "<LOC Unit_Description_0009> Adds a short-range tactical nuke."
Description['gel0001-pst'] = "<LOC Unit_Description_GCE002> Adds Superteleport. Not requires considerable Energy to activate."
Description['gel0001-sgf'] = "<LOC Unit_Description_0011> Expands the radius of the ACU's personal shield. Requires Energy to run."
Description['gel0001-isb'] = "<LOC Unit_Description_0012> Increases ACU's resource generation."
Description['gel0001-ps1'] = "<LOC Unit_Description_0013> Creates a protective shield around the ACU. Requires Energy to run."
Description['gel0001-ps2'] = "<LOC Unit_Description_GCE040> Expands the hitpoints and regenrate of the ACU's personal shield. Requires Energy to run."
Description['gel0001-ps3'] = "<LOC Unit_Description_GCE041> Second expands the hitpoints and regenrate of the ACU's personal shield. Requires Energy to run."
Description['gel0001-hpsg'] = "<LOC Unit_Description_GCE042> Third expands the hitpoints and regenrate of the ACU's personal shield. Requires Energy to run."
Description['gel0001-led'] = "<LOC Unit_Description_0014> Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable."
Description['gel0001-red'] = "<LOC Unit_Description_0015> Adds a second Engineering Drone. Requires an initial Engineering Drone."
Description['gel0001-asc'] = "<LOC Unit_Description_GCE003> Equips the ACU with a Heavy Plasma Cannon."
Description['gel0001-mc'] = "<LOC Unit_Description_GCE004> Equips the ACU with a Mega Cannon."
Description['gel0001-mc2'] = "<LOC Unit_Description_GCE005> Equips the ACU with a second Mega Cannon."
Description['gel0001-torp'] = "<LOC Unit_Description_GCE006> Equips the ACU with a powerful Rapidfire Torpedo Launcher."
Description['gel0001-aa'] = "<LOC Unit_Description_GCE007> Equips the ACU with anti-air missile system."
Description['gel0001-ar'] = "<LOC Unit_Description_GCE008> Increases ACU maximum health."
Description['gel0001-mg'] = "<LOC Unit_Description_GCE009> Equips the ACU with a six barrels Miniguns."
Description['gel0001-glas'] = "<LOC Unit_Description_GCE010> Equips the ACU with a Heavy Shoulder Cannon."
Description['gel0001-t4'] = "<LOC Unit_Description_GCE011> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gel0001-spd'] = "<LOC Unit_Description_GCE012> Increase ACU move speed."
Description['gel0001-cml'] = "<LOC Unit_Description_GCE013> Equips the ACU with Cluster Missile Launcher."
Description['gel0001-sre'] = "<LOC Unit_Description_0159> Greatly expands the range of the standard onboard ACU sensor systems."
Description['gel0001-rj'] = "<LOC Unit_Description_0020> Radar Jammer creates false radar images. Countered by Omni sensors."
Description['gel0001-huk'] = "<LOC Unit_Description_GCE014> Enable Hunker Mode."
Description['gel0001-rfg'] = "<LOC Unit_Description_GCE015> Add Repair Field Generator."
Description['gel0001-rrf'] = "<LOC Unit_Description_GCE016> Add Remote Repair Field."
Description['gel0001-acu'] = "<LOC Unit_Description_GCE017> Increases main cannon rate of fire."
Description['gel0001-sg'] = "<LOC Unit_Description_GCE018> Increases main cannon damage."
Description['gel0001-heo'] = "<LOC Unit_Description_GCE019> Increases main cannon splash damage."
Description['gel0001-iemes'] = "<LOC Unit_Description_GCE020> Equips the ACU with Orbital Bombardment Device."

##UEF SCU Upgrades  

Description['uel0301'] = "<LOC Unit_Description_0016> A multi-purpose construction, repair, capture and reclamation unit. Equivalent to a Tech 3 Engineer."
Description['uel0301-led'] = "<LOC Unit_Description_GCE021> Engineering Drone acts as a secondary Engineer. Assists the SCU where applicable."
Description['uel0301-red'] = "<LOC Unit_Description_GCE022> Adds a second Engineering Drone. Requires an initial Engineering Drone."
Description['uel0301-psg'] = "<LOC Unit_Description_0018> Creates a protective shield around the SACU. Requires Energy to run."
Description['uel0301-sgf'] = "<LOC Unit_Description_0019> Expands the radius of the SACU's personal shield. Requires Energy to run."
Description['uel0301-rj'] = "<LOC Unit_Description_0020> Radar Jammer creates false radar images. Countered by Omni sensors."
Description['uel0301-isb'] = "<LOC Unit_Description_0021> Increases SACU's resource generation."
Description['uel0301-sre'] = "<LOC Unit_Description_0022> Greatly expands the range of the standard onboard SACU sensor systems."
Description['uel0301-acu'] = "<LOC Unit_Description_GCE023> Increases Rate of Fire for Shotguns."
Description['uel0301-heo'] = "<LOC Unit_Description_GCE024> Increases Splash Damage for Shotguns."
Description['uel0301-sg'] = "<LOC Unit_Description_GCE025> Increases Damage for Shotguns."
Description['uel0301-mg'] = "<LOC Unit_Description_GCE026> Equips the SCU with a six barrels Miniguns."
Description['uel0301-tm'] = "<LOC Unit_Description_GCE027> Equips the SCU with Napalm Missile Launcher."
Description['uel0301-asc'] = "<LOC Unit_Description_GCE028> Equips the SCU with a Heavy PlasmaGun."
Description['uel0301-aa'] = "<LOC Unit_Description_GCE029> Equips the SCU with anti-air missile system."
Description['uel0301-spd'] = "<LOC Unit_Description_GCE030> Increase SCU move speed."
Description['uel0301-pst'] = "<LOC Unit_Description_GCE002> Adds Superteleport. Not requires considerable Energy to activate."
Description['uel0301-dsu'] = "<LOC Unit_Description_GCE031> Greatly increases the speed at which the SCU repairs itself."
Description['uel0301-t4'] = "<LOC Unit_Description_GCE032> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['uel0301-t5'] = "<LOC Unit_Description_GCE033> Replaces the Tech 4 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."

##UEF Experimental Upgrades

Description['uel0401-isb'] = "<LOC Unit_Description_GCE034> Add Fatboy resource generation."
Description['uel0401-efm'] = "<LOC Unit_Description_GCE035> Increases Fatboy Build Rate."
Description['ues0401-isb'] = "<LOC Unit_Description_GCE036> Add Atlantis resource generation."
Description['ues0401-exp'] = "<LOC Unit_Description_GCE037> Add Atlantis experimental tech level."
Description['ueb2401-psg'] = "<LOC Unit_Description_GCE038> Creates a protective shield around the Mavor. Requires Energy to run."
Description['ueb2401-sgf'] = "<LOC Unit_Description_GCE039> Expands the radius of the Mavor personal shield. Requires Energy to run."

##Aeon ACU Upgrades

Description['gal0001'] = "<LOC Unit_Description_0305> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
Description['gal0001-aes'] = "<LOC Unit_Description_0156> Expands the number of available schematics and increases the ACU's build speed and maximum health."
Description['gal0001-cba'] = "<LOC Unit_Description_GCA001> Increases ACUs Main Gun maximum range."
Description['gal0001-ess'] = "<LOC Unit_Description_0159> Greatly expands the range of the standard onboard ACU sensor systems."
Description['gal0001-ees'] = "<LOC Unit_Description_0160> Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gal0001-hsa'] = "<LOC Unit_Description_GCA002> Increases ACUs Main Gun rate of fire."
Description['gal0001-ras'] = "<LOC Unit_Description_0162> Increases ACU's resource generation."
Description['gal0001-eras'] = "<LOC Unit_Description_0163> Requires Resource Allocation System. Further increases ACU's resource generation."
Description['gal0001-ptsg'] = "<LOC Unit_Description_0164> Creates a protective shield around the ACU. Requires Energy to run."
Description['gal0001-phtsg'] = "<LOC Unit_Description_0165> Enhances the protective shield around the ACU. Requires Energy to run."
Description['gal0001-sic'] = "<LOC Unit_Description_0006> Greatly increases the speed at which the ACU repairs itself."
Description['gal0001-pst'] = "<LOC Unit_Description_GCA003> Adds Superteleport. Not requires Energy to activate."
Description['gal0001-qc'] = "<LOC Unit_Description_GCA004> Equips the ACU with heavy Quantum Cannon."
Description['gal0001-aa'] = "<LOC Unit_Description_GCA005> Equips the ACU with anti-air missile system."
Description['gal0001-mm'] = "<LOC Unit_Description_GCA006> Equips the ACU with a rapidfire Missile Launcher."
Description['gal0001-phl'] = "<LOC Unit_Description_GCA007> Equips the ACU with a deadly powerful Phason Laser."
Description['gal0001-ob'] = "<LOC Unit_Description_GCA008> Equips the ACU with a powerful Oblivion Cannon."
Description['gal0001-t4'] = "<LOC Unit_Description_GCA009> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gal0001-torp'] = "<LOC Unit_Description_GCA010> Equips the ACU with a rapidfire Torpedo Launcher."
Description['gal0001-emm'] = "<LOC Unit_Description_GCA011> Adds ACU EMP Missile Launcher."
Description['gal0001-cml'] = "<LOC Unit_Description_GCA012> Increases EMP Missile Launcher Rate of Fire."
Description['gal0001-rvd'] = "<LOC Unit_Description_GCA013> Adds ACU Remote Viewing Divice."
Description['gal0001-ar'] = "<LOC Unit_Description_GCA014> Increases ACUs maximum health."
Description['gal0001-ss'] = "<LOC Unit_Description_GCA015> Increases ACUs Main Gun Slash Damage."
Description['gal0001-pup'] = "<LOC Unit_Description_GCA016> Increases ACUs Main Gun Damage."
Description['gal0001-srs'] = "<LOC Unit_Description_GCA017> Increases ACUs move speed."
Description['gal0001-huk'] = "<LOC Unit_Description_GCA018> Enable Hunker Mode."
Description['gal0001-lrd'] = "<LOC Unit_Description_GCA019> Resource Drone. Increases ACUs resource generation."
Description['gal0001-rrd'] = "<LOC Unit_Description_GCA020> Adds a second Resource Drone. Requires an initial Resource Drone."

##Aeon SCU Upgrades 

Description['ual0301'] = "<LOC Unit_Description_0167> A multi-purpose construction, repair, capture and reclamation unit. Equivalent to a Tech 3 Engineer."
Description['ual0301-efm'] = "<LOC Unit_Description_0168> Speeds up all engineering-related functions."
Description['ual0301-sic'] = "<LOC Unit_Description_0174> Greatly increases the speed at which the SACU repairs itself."
Description['ual0301-ess'] = "<LOC Unit_Description_0022> Greatly expands the range of the standard onboard SACU sensor systems."
Description['ual0301-ptsg'] = "<LOC Unit_Description_GCA021> Creates a protective shield around the SCU. Requires Energy to run."
Description['ual0301-phtsg'] = "<LOC Unit_Description_GCA022> Enhances the protective shield around the SCU. Requires Energy to run."
Description['ual0301-pst'] = "<LOC Unit_Description_GCA023> Adds Superteleporter. Not requires considerable Energy to activate."
Description['ual0301-aa'] = "<LOC Unit_Description_GCA024> Equips the SCU with anti-air missile system."
Description['ual0301-cml'] = "<LOC Unit_Description_GCA025> Equips the SCU with a Cruise Missile Launcher."
Description['ual0301-srs'] = "<LOC Unit_Description_GCA026> Increase SCU move speed."
Description['ual0301-ras'] = "<LOC Unit_Description_GCA027> Increases SCU's resource generation."
Description['ual0301-eras'] = "<LOC Unit_Description_GCA028> Further increases SCU's resource generation."
Description['ual0301-phl'] = "<LOC Unit_Description_GCA029> Equips the SCU with a deadly powerful Phason Laser."
Description['ual0301-qc'] = "<LOC Unit_Description_GCA030> Equips the SCU with heavy Quantum Cannon."
Description['ual0301-cba'] = "<LOC Unit_Description_GCA031> Increases Damage for Oblivion Cannon."
Description['ual0301-hsa'] = "<LOC Unit_Description_GCA032> Increases Rate of Fire for Oblivion Cannon."
Description['ual0301-ss'] = "<LOC Unit_Description_GCA033> Increases Splash Damage for Oblivion Cannon."
Description['ual0301-torp'] = "<LOC Unit_Description_GCA034> Equips the SCU with a rapidfire Torpedo Launcher."
Description['ual0301-t4'] = "<LOC Unit_Description_GCA035> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['ual0301-t5'] = "<LOC Unit_Description_GCA036> Replaces the Tech 4 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."

##Aeon Experimental Upgrades

Description['uaa0310-eras'] = "<LOC Unit_Description_GCA037> Add CZAR resource generation."
Description['uaa0310-efm'] = "<LOC Unit_Description_GCA038> Increases CZAR Build Rate."
Description['uas0401-eras'] = "<LOC Unit_Description_GCA039> Add Tempest resource generation."
Description['uas0401-efm'] = "<LOC Unit_Description_GCA040> Increases Tempest Build Rate."
Description['xab1401-ptsg'] = "<LOC Unit_Description_GCA041> Creates a protective shield around the Paragon. Requires Energy to run."
Description['xab1401-phtsg'] = "<LOC Unit_Description_GCA042> Enhances the protective shield around the Paragon. Requires Energy to run."

##Cybran ACU Upgrades

Description['grl0001'] = "<LOC Unit_Description_0304> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch." 
Description['grl0001-ras'] = "<LOC Unit_Description_0106> Increases ACU's resource generation."
Description['grl0001-eras'] = "<LOC Unit_Description_0163> Requires Resource Allocation System. Further increases ACU's resource generation."
Description['grl0001-pcg'] = "<LOC Unit_Description_0107> Cloaks the ACU from optical sensors and increases maximum health. Can be detected by Omni Sensors. Requires Energy to run."
Description['grl0001-psg'] = "<LOC Unit_Description_0108> Hides the ACU from radar. Requires Energy to run."
Description['grl0001-aa'] = "<LOC Unit_Description_0119> Adds AA defensive system."
Description['grl0001-aes'] = "<LOC Unit_Description_0110> Expands the number of available schematics and increases the ACU's build speed and maximum health."
Description['grl0001-ees'] = "<LOC Unit_Description_0111> Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['grl0001-mlg'] = "<LOC Unit_Description_0113> ACU can generate a beam laser that sweeps over enemy units."
Description['grl0001-ntt'] = "<LOC Unit_Description_GCR001> Equips the ACU with a rapidfire Torpedo Launcher."
Description['grl0001-ess'] = "<LOC Unit_Description_0159> Greatly expands the range of the standard onboard ACU sensor systems."
Description['grl0001-srs'] = "<LOC Unit_Description_0006> Greatly increases the speed at which the ACU repairs itself."
Description['grl0001-mrsen'] = "<LOC Unit_Description_GCR002> Equips the ACU with EMP missile launcher."
Description['grl0001-sic'] = "<LOC Unit_Description_GCR003> Increase ACU move speed."
Description['grl0001-pst'] = "<LOC Unit_Description_GCR004> Adds Superteleporter. Not requires considerable Energy to activate."
Description['grl0001-artas'] = "<LOC Unit_Description_GCR005> Equips the ACU with an Advanced Molecular Ripper."
Description['grl0001-sdu'] = "<LOC Unit_Description_GCR005> Equips the ACU with a powerful Heavy Proton Cannon."
Description['grl0001-art'] = "<LOC Unit_Description_GCR006> Equips the ACU with a rapidfire Proton Artillery."
Description['grl0001-ar'] = "<LOC Unit_Description_GCR007> Increases ACU maximum health."
Description['grl0001-tmd'] = "<LOC Unit_Description_GCR008> Equips the ACU with a tactical missile defense."
Description['grl0001-smd'] = "<LOC Unit_Description_GCR009> Equips the ACU with a strategic missile defense."
Description['grl0001-t4'] = "<LOC Unit_Description_GCR010> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['grl0001-fc'] = "<LOC Unit_Description_GCR011> Increases Damage for Molecular Ripper."
Description['grl0001-acu'] = "<LOC Unit_Description_GCR012> Increases Rate of Fire for Molecular Ripper."
Description['grl0001-eru'] = "<LOC Unit_Description_GCR013> Increases Range for Molecular Ripper."
Description['grl0001-bmlg'] = "<LOC Unit_Description_GCR014> Increases Damage, Rate of Fire and Splash Damage for ACU's microwave laser."
Description['grl0001-huk'] = "<LOC Unit_Description_GCR015> Enable Hunker Mode."
Description['grl0001-cfs'] = "<LOC Unit_Description_GCR016> Adds Remote Cloaking Divice."
Description['grl0001-ad'] = "<LOC Unit_Description_GCR017> Adds two Assault Drones."

##Cybran SCU Upgrades

Description['url0301'] = "<LOC Unit_Description_0115> A multi-purpose construction, repair, capture and reclamation unit. Equivalent to a Tech 3 Engineer."
Description['url0301-cfs'] = "<LOC Unit_Description_0116> Cloaks the SACU from optical sensors. Can be detected by Omni Sensors. Requires Energy to run."
Description['url0301-emp'] = "<LOC Unit_Description_GCR018> Adds EMP Laser."
Description['url0301-nms'] = "<LOC Unit_Description_0119> Adds AA defensive system."
Description['url0301-ses'] = "<LOC Unit_Description_0121> Speeds up all engineering-related functions."
Description['url0301-srs'] = "<LOC Unit_Description_0122> Greatly increases the speed at which the SACU repairs itself."
Description['url0301-sfs'] = "<LOC Unit_Description_0123> Hides the SACU from radar. Requires Energy to run."
Description['url0301-ess'] = "<LOC Unit_Description_0022> Greatly expands the range of the standard onboard SACU sensor systems."
Description['url0301-artas'] = "<LOC Unit_Description_GCR019> Equips the SCU with a Proton Cannon."
Description['url0301-fc'] = "<LOC Unit_Description_GCR020> Increases Damage for Ripper Cannon."
Description['url0301-acu'] = "<LOC Unit_Description_GCR021> Increases Rate of Fire for Ripper Cannon."
Description['url0301-sdu'] = "<LOC Unit_Description_GCR022> Increases Splash Damage for Ripper Cannon."
Description['url0301-mlg'] = "<LOC Unit_Description_GCR023> SCU can generate a beam laser that sweeps over enemy units."
Description['url0301-ras'] = "<LOC Unit_Description_GCR024> Increases SCU's resource generation."
Description['url0301-eras'] = "<LOC Unit_Description_GCR025> Further increases SCU's resource generation."
Description['url0301-ar'] = "<LOC Unit_Description_GCR026> Increases SCU maximum health."
Description['url0301-jp'] = "<LOC Unit_Description_GCR027> Adds jetpack. SCU can flight."
Description['url0301-ntt'] = "<LOC Unit_Description_GCR028> Equips the SCU with a rapidfire Torpedo Launcher."
Description['url0301-art'] = "<LOC Unit_Description_GCR029> Equips the SCU with powerful Proton Artillery."
Description['url0301-t4'] = "<LOC Unit_Description_GCR030> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['url0301-t5'] = "<LOC Unit_Description_GCR031> Replaces the Tech 4 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
 
Description['ura0301'] = "<LOC Unit_Description_0115> A multi-purpose construction, repair, capture and reclamation unit. Equivalent to a Tech 3 Engineer."
Description['ura0301-cfs'] = "<LOC Unit_Description_0116> Cloaks the SACU from optical sensors. Can be detected by Omni Sensors. Requires Energy to run."
Description['ura0301-emp'] = "<LOC Unit_Description_GCR018> Adds EMP Laser."
Description['ura0301-nms'] = "<LOC Unit_Description_0119> Adds AA defensive system."
Description['ura0301-ses'] = "<LOC Unit_Description_0121> Speeds up all engineering-related functions."
Description['ura0301-srs'] = "<LOC Unit_Description_0122> Greatly increases the speed at which the SACU repairs itself."
Description['ura0301-sfs'] = "<LOC Unit_Description_0123> Hides the SACU from radar. Requires Energy to run."
Description['ura0301-ess'] = "<LOC Unit_Description_0022> Greatly expands the range of the standard onboard SACU sensor systems."
Description['ura0301-artas'] = "<LOC Unit_Description_GCR019> Equips the SCU with a Proton Cannon."
Description['ura0301-fc'] = "<LOC Unit_Description_GCR020> Increases Damage for Ripper Cannon."
Description['ura0301-acu'] = "<LOC Unit_Description_GCR021> Increases Rate of Fire for Ripper Cannon."
Description['ura0301-sdu'] = "<LOC Unit_Description_GCR022> Increases Splash Damage for Ripper Cannon."
Description['ura0301-mlg'] = "<LOC Unit_Description_GCR023> SCU can generate a beam laser that sweeps over enemy units."
Description['ura0301-ras'] = "<LOC Unit_Description_GCR024> Increases SCU's resource generation."
Description['ura0301-eras'] = "<LOC Unit_Description_GCR025> Further increases SCU's resource generation."
Description['ura0301-ar'] = "<LOC Unit_Description_GCR026> Increases SCU maximum health."
Description['ura0301-jp'] = "<LOC Unit_Description_GCR027> Adds jetpack. SCU can flight."
Description['ura0301-ntt'] = "<LOC Unit_Description_GCR028> Equips the SCU with a rapidfire Torpedo Launcher."
Description['ura0301-art'] = "<LOC Unit_Description_GCR029> Equips the SCU with powerful Proton Artillery."
Description['ura0301-t4'] = "<LOC Unit_Description_GCR030> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['ura0301-t5'] = "<LOC Unit_Description_GCR031> Replaces the Tech 4 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."

##Cybran Experimental Upgrades

Description['url0401-emp'] = "<LOC Unit_Description_GCR032> Add EMP burst."
Description['xrl0403-eras'] = "<LOC Unit_Description_GCR033> Add Megalith resource generation."
Description['xrl0403-ses'] = "<LOC Unit_Description_GCR034> Increases Megalith Build Rate."
Description['xrl0405-eras'] = "<LOC Unit_Description_GCR035> Add Brackman resource generation."
Description['xrl0405-ses'] = "<LOC Unit_Description_GCR036> Increases Brackman Build Rate."

##Serephim ACU Upgrades

Description['gsl0001'] = "<LOC Unit_Description_0420> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
Description['gsl0001-dss'] = "<LOC Unit_Description_0422> Increases the speed at which the ACU repairs itself. Also increases hit points."
Description['gsl0001-adss'] = "<LOC Unit_Description_0454> Further increases the speed at which the ACU repairs itself. Also increases hitpoints."
Description['gsl0001-ras'] = "<LOC Unit_Description_0424> Increases ACU's resource generation."
Description['gsl0001-eras'] = "<LOC Unit_Description_0425> Requires Resource Allocation System. Further increases ACU's resource generation."
Description['gsl0001-aes'] = "<LOC Unit_Description_0426> Expands the number of available schematics and increases the ACU's build speed and maximum health."
Description['gsl0001-ees'] = "<LOC Unit_Description_0427> Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gsl0001-nrf'] = "<LOC Unit_Description_0429> Automatically speeds up the repair speed of nearby units."
Description['gsl0001-anrf'] = "<LOC Unit_Description_0430> Further speeds up the repair speed of nearby units. Increases maximum health of nearby units."
Description['gsl0001-sre'] = "<LOC Unit_Description_0159> Greatly expands the range of the standard onboard ACU sensor systems."
Description['gsl0001-sp'] = "<LOC Unit_Description_0013> Creates a protective shield around the ACU. Requires Energy to run."
Description['gsl0001-phsg'] = "<LOC Unit_Description_0165> Enhances the protective shield around the ACU. Requires Energy to run."
Description['gsl0001-pqt'] = "<LOC Unit_Description_GCS001> Adds superteleporter. Not requires considerable Energy to activate."
Description['gsl0001-ldg'] = "<LOC Unit_Description_GCS002> Increases Main Cannon's range."
Description['gsl0001-hsa'] = "<LOC Unit_Description_GCS003> Increases Main Cannon's rate of fire."
Description['gsl0001-cba'] = "<LOC Unit_Description_GCS004> Increases Main Cannon's damage."
Description['gsl0001-sde'] = "<LOC Unit_Description_GCS005> Increases Main Cannon's splash damage."
Description['gsl0001-tmu'] = "<LOC Unit_Description_GCS006> Equips the ACU with Redirect Missile Divice."
Description['gsl0001-lgfas'] = "<LOC Unit_Description_GCS007> Equips the ACU with a powerful Experimental Bigball Cannon."
Description['gsl0001-t4'] = "<LOC Unit_Description_GCS008> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health."
Description['gsl0001-aa'] = "<LOC Unit_Description_GCS009> Equips the ACU with Anti-Air Missile Launcher."
Description['gsl0001-oc'] = "<LOC Unit_Description_GCS010> Equips the ACU with Power Cannon."
Description['gsl0001-pghsa'] = "<LOC Unit_Description_GCS011> Increases Power Cannon's rate of fire and range."
Description['gsl0001-pgsde'] = "<LOC Unit_Description_GCS012> Increases the damage inflicted by Power Cannon. Adds area-of-effect damage."
Description['gsl0001-mg'] = "<LOC Unit_Description_GCS013> Equips the ACU with a rapidfire MiltiGun."
Description['gsl0001-stmd'] = "<LOC Unit_Description_GCS014> Equips the ACU with Tactical Missile Defense."
Description['gsl0001-torp'] = "<LOC Unit_Description_GCS015> Equips the ACU with a rapidfire Torpedo Launcher."
Description['gsl0001-nlg'] = "<LOC Unit_Description_GCS016> Equips the ACU with Nuke Laser."
Description['gsl0001-jp'] = "<LOC Unit_Description_GCS017> Increase ACU move speed."
Description['gsl0001-huk'] = "<LOC Unit_Description_GCS018> Enable Hunker Mode."
Description['gsl0001-led'] = "<LOC Unit_Description_0014> Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable."
Description['gsl0001-red'] = "<LOC Unit_Description_0015> Adds a second Engineering Drone. Requires an initial Engineering Drone."
Description['gsl0001-rtd'] = "<LOC Unit_Description_GCS038> Adds ACU Remote Tracking Divice."

##Serephim SCU Upgrades

Description['xsl0301'] = "<LOC Unit_Description_0433> A multi-purpose construction, repair, capture and reclamation unit. Equivalent to a Tech 3 Engineer."
Description['xsl0301-tnm'] = "<LOC Unit_Description_0009> Adds a short-range tactical nuke."
Description['xsl0301-dss'] = "<LOC Unit_Description_0435> Increases the speed at which the SACU repairs itself. Also increases hit points."
Description['xsl0301-sre'] = "<LOC Unit_Description_0436> Greatly expands the range of the standard onboard SACU sensor systems, including Omni."
Description['xsl0301-efm'] = "<LOC Unit_Description_0437> Speeds up all engineering-related functions."
Description['xsl0301-sp'] = "<LOC Unit_Description_0438> Adds a personal shield generator to the SACU."
Description['xsl0301-oc'] = "<LOC Unit_Description_GCS019> Equips the SCU with Overcharge Cannon."
Description['xsl0301-pqt'] = "<LOC Unit_Description_GCS020> Adds superteleporter. Not requires considerable Energy to activate."
Description['xsl0301-eb'] = "<LOC Unit_Description_GCS021> Equips the SCU with a deadly powerful Demolishen Laser."
Description['xsl0301-jp'] = "<LOC Unit_Description_GCS022> Increase SCU move speed."
Description['xsl0301-ras'] = "<LOC Unit_Description_GCS023> Increases SCU's resource generation."
Description['xsl0301-eras'] = "<LOC Unit_Description_GCS024> Further increases SCU's resource generation."
Description['xsl0301-aa'] = "<LOC Unit_Description_GCS025> Equips the SCU with Anti-Air Lightning Generator."
Description['xsl0301-torp'] = "<LOC Unit_Description_GCS026> Equips the SCU with a Torpedo Launcher."
Description['xsl0301-hsa'] = "<LOC Unit_Description_GCS027> Increases Main Cannon's rate of fire."
Description['xsl0301-cba'] = "<LOC Unit_Description_GCS028> Increases Main Cannon's damage."
Description['xsl0301-sde'] = "<LOC Unit_Description_GCS029> Increases Main Cannon's splash damage."
Description['xsl0301-lgfas'] = "<LOC Unit_Description_GCS030> Equips the SCU with Heavy Quarnon Cannon."
Description['xsl0301-t4'] = "<LOC Unit_Description_GCS031> Replaces the Tech 3 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['xsl0301-t5'] = "<LOC Unit_Description_GCS032> Replaces the Tech 4 Engineering Suite. Expands the number of available schematics and further increases the SCU's build speed and maximum health."
Description['xsl0301-rtd'] = "<LOC Unit_Description_GCS038> Adds SCU Remote Tracking Divice."

##Serephim Experimental Upgrades

Description['xsb2401-sp'] = "<LOC Unit_Description_GCS033> Creates a protective shield around the Yolona Oss. Requires Energy to run."
Description['xsb2401-phsg'] = "<LOC Unit_Description_GCS034> Enhances the protective shield around the Yolona Oss. Requires Energy to run."
Description['xsb2401-lgfas'] = "<LOC Unit_Description_GCS035> Replaces original nuke missile on advanced warhead."
Description['xsl0403-eras'] = "<LOC Unit_Description_GCS036> Add Deathium resource generation."
Description['xsl0403-efm'] = "<LOC Unit_Description_GCS037> Increases Deathium Build Rate."
